-- CreateTable
CREATE TABLE "public"."bio_data" (
    "id" TEXT NOT NULL,
    "full_name" TEXT NOT NULL,
    "date_of_birth" TIMESTAMP(3) NOT NULL,
    "place_of_birth" TEXT NOT NULL,
    "nationality" TEXT NOT NULL,
    "height" TEXT NOT NULL,
    "weight" TEXT NOT NULL,
    "name_of_airPort" TEXT NOT NULL,
    "marital_status" TEXT NOT NULL,
    "religion" TEXT NOT NULL,
    "education_level" TEXT NOT NULL,
    "age_of_childern" TEXT NOT NULL,
    "number_of_childern" TEXT NOT NULL,
    "image" TEXT,
    "allergies" BOOLEAN NOT NULL DEFAULT false,
    "physical_disabilities" BOOLEAN NOT NULL DEFAULT false,
    "mental_illness" BOOLEAN NOT NULL DEFAULT false,
    "epilepsy" BOOLEAN NOT NULL DEFAULT false,
    "tuberculosis" BOOLEAN NOT NULL DEFAULT false,
    "heart_disease" BOOLEAN NOT NULL DEFAULT false,
    "malaria" BOOLEAN NOT NULL DEFAULT false,
    "operations" BOOLEAN NOT NULL DEFAULT false,
    "others" TEXT,
    "dietary_restrictions" BOOLEAN NOT NULL DEFAULT false,
    "preference_for_rest_days" BOOLEAN NOT NULL DEFAULT false,
    "any_other_remarks" TEXT,
    "area_of_work_one" TEXT,
    "willingness_one" BOOLEAN NOT NULL DEFAULT false,
    "experience_one" BOOLEAN NOT NULL DEFAULT false,
    "assessment_or_observation_one" TEXT,
    "area_of_work_two" TEXT,
    "willingness_two" BOOLEAN NOT NULL DEFAULT false,
    "experience_two" BOOLEAN NOT NULL DEFAULT false,
    "assessment_or_observation_two" TEXT,
    "area_of_work_three" TEXT,
    "willingness_three" BOOLEAN NOT NULL DEFAULT false,
    "experience_three" BOOLEAN NOT NULL DEFAULT false,
    "assessment_or_observation_three" TEXT,
    "area_of_work_four" TEXT,
    "willingness_four" BOOLEAN NOT NULL DEFAULT false,
    "experience_four" BOOLEAN NOT NULL DEFAULT false,
    "assessment_or_observation_four" TEXT,
    "area_of_work_five" TEXT,
    "willingness_five" BOOLEAN NOT NULL DEFAULT false,
    "experience_five" BOOLEAN NOT NULL DEFAULT false,
    "assessment_or_observation_five" TEXT,
    "area_of_work_six" TEXT,
    "willingness_six" BOOLEAN NOT NULL DEFAULT false,
    "experience_six" BOOLEAN NOT NULL DEFAULT false,
    "assessment_or_observation_six" TEXT,
    "area_of_work_seven" TEXT,
    "willingness_seven" BOOLEAN NOT NULL DEFAULT false,
    "experience_seven" BOOLEAN NOT NULL DEFAULT false,
    "assessment_or_observation_seven" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "bio_data_pkey" PRIMARY KEY ("id")
);
